### ISSUE TITLE
scan.yml action to use the main action

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-dev/rumble#23]
[scan.yml](https://github.com/chainguard-dev/rumble/blob/main/.github/workflows/scan.yml) is currently not using the github action provided by this repo.

modify the action to allow BigQuery writes and disable attestation

**Comment by jdolitsky** [comment]
Example (trivy):
```yaml
    - uses: chainguard-dev/rumble@main
      with:
        image: "${{ matrix.apkoBaseTag }}:${{ matrix.apkoTargetTag }}"
        scanner: trivy
```
